### PR TITLE
fix: UI changes

### LINKED ISSUE #44: Vital cosmetic UX fix
Issue #1: when WR was a plug-in it integrated smoothly with the PSS/audience browser drop down. 
Proposal: can we force the stream to go full screen on play; play for 5-7 seconds before drop down (identification time); drop down into full screen of film

Issue #2: drop down should be movie poster size / ratio 
Proposal: change to 27" x 40" ratio

Issue #3: payment time confirmation time 
Proposal: max 3 seconds (now 4)

Issue #4: change thumbs up above "Thank you for being a responsible rebel" 
Proposal: White Rabbit logo instead of a thumb and hold for 1 second longer

## Scope

- [x] streamer: show video stream full-screen
- [x] streamer: request payment in 7 seconds (implemented in #43)
- [x] app: use poster ratio (27/40) for app size
- [x] app: use White Rabbit logo on Acknowledgement page instead of big emoji
- [x] app: keep Acknowledgement page open for 4 seconds (not 3 seconds as it is now)

## Roles

gardener: @troggy 30 DAI
worker: @troggy (#43 only) + @Clearwood
reviewer: @troggy

### PR DESCRIPTION
**Pull request by Clearwood**
Please remember the [Contributing Guidelines](https://github.com/leapdao/meta/blob/master/CONTRIBUTION.md) :heart:

## What does this PR do?

1. Opens a nearly full screen video
2. Changes the format of the popup to movie poster size
3. Adds the White rabbit logo on the appreciation site. 

## Recommendations for testing

npm run start-local
Navigate to http://localhost:1234

## Links to relevant issues or information

Closes #44

### CODE REVIEW

File: packages/burner-plugin/src/ui/PaidMoviePage.tsx [hunk 1]
```diff
@@ -2,6 +2,7 @@ import React, { useEffect, useState } from 'react';
 import { RouteComponentProps } from 'react-router-dom';
 import styled from 'styled-components';
 import { BurnerContext, withBurner } from '@burner-wallet/ui-core';
+const logo = require('./images/White-rabbit-logo-white.png');
```
Comment (troggy) [inline packages/burner-plugin/src/ui/PaidMoviePage.tsx:5]: this file is missing in PR

File: packages/burner-plugin/package.json [hunk 2]
```diff
@@ -32,10 +32,10 @@
     "typescript": "^3.8.3"
   },
   "scripts": {
-    "css": "copyfiles -u 1 \"src/**/*.css\" dist/",
+    "css": "copyfiles -u 1 \"src/**/*.css\" dist/ && copyfiles -u 1 \"src/ui/images/*.png\" dist/",
```
Comment (troggy) [inline packages/burner-plugin/package.json:35]: we don't have CSS files anymore and I forgot to remove `css` script. So I suggest the following:
1. keep images in `packages/burner-wplguin/public/images`
2. replace `css` npm script with `"public": "copyfiles -u 1 \"public/**/*\" dist/"`

Comment (troggy) [reply packages/burner-plugin/package.json:35]: this is future-proof IMO: we can put everything that needs to be made public as-is in a `public` folder, no need to change scripts

**Comment by troggy** [comment]
@Right2Rebel is it what you had in mind? Check the demo here: https://wr-streamer-preview-ui.netlify.app/
